---
abstract: 'Modern designer-friendly HTML templating Engine'
author:
  - 'Stefan Hornburg (Racke) <racke@linuxia.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Flute
no_index:
  directory:
    - t
    - inc
requires:
  File::Slurp: 0
  HTML::TreeBuilder: 0
  Moo: 0
  Parse::RecDescent: 0
  Scalar::Util: 0
  Test::Deep: 0
  Test::Fatal: 0
  Test::More: 0
  Test::Warn: 0
  Test::Warnings: 0
  URI: 0
  XML::Twig: 0
resources:
  bugtracker: https://github.com/racke/Template-Flute/issues
  repository: https://github.com/racke/Template-Flute.git
version: 0.0107
